### PR TITLE
Add to local storage

### PR DESCRIPTION
**Pull request by Shurtu-gal**

### CODE REVIEW

**Comment by Shurtu-gal** [comment]
Don't merge it yet.

**Comment by Shurtu-gal** [comment]
Got to fine tune it.

**Comment by Shurtu-gal** [comment]
Let's invite others also as contributors.

**Review by Shurtu-gal — COMMENTED** [review]
This is a great addition.

**Comment by Shurtu-gal** [comment]
I think can make a master id for retrieval.

**Comment by s-m33r** [comment]
What do you mean by master ID ? Isn't the random key that's currently used for local storage entries kind of like a master ID ?

**Review by s-m33r — COMMENTED** [review]
Just gonna change prompt() to confirm() to ask more directly.

**Comment by s-m33r** [comment]
pls take a look. I'll merge these then

**Pull request merged**
